default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: <%= ENV.fetch('database_username') %>
  password: <%= ENV.fetch('database_password') %>
  host: <%= ENV.fetch('database_host') %>

development:
  <<: *default
  database: <%= ENV.fetch('database_name_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('database_name_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('database_name_production') %>
